language: android
android:
 components:
  # Uncomment the lines below if you want to
  # use the latest revision of Android SDK Tools
  - tools
  - platform-tools
  - tools

  # The BuildTools version used by your project
  - build-tools-26.0.0

  # The SDK version used to compile your project
  - android-26

  # Additional components
  - extra-android-support
  - extra-android-m2repository

  # Specify at least one system image,
  # if you need to run emulator(s) during your tests

install:
 - echo y | android update sdk -u -a -t tools
 - echo y | android update sdk -u -a -t platform-tools
 - echo y | android update sdk -u -a -t build-tools-25.0.2
 - echo y | android update sdk -u -a -t android-25
 - echo y | android update sdk -u -a -t extra-google-m2repository
 - echo y | android update sdk -u -a -t extra-android-m2repository

script:
 - ./gradlew build connectedCheck

branches:
 only:
   - master

after_failure: "cat $TRAVIS_BUILD_DIR/app/build/reports/lint-results.xml"